BPETextField:
  version: 2.0
  data_processed: data_for_galaxy_encoded.data.json
  filtered: false
  max_len: 1024
  min_utt_len: 1
  max_utt_len: 50
  min_ctx_turn: 1
  max_ctx_turn: 20
  tokenizer_type: Bert
  
Dataset: 
  data_dir: null
  data_name: multiwoz

Trainer:
  seed: 10
  gpu: 1
  valid_metric_name: -loss
  num_epochs: 10
  token_loss: true
  batch_size: 1
  log_steps: 100
  valid_steps: 2000
  save_checkpoint: true
  shuffle: true
  sort_pool_size: 0

Model:
  model: UnifiedTransformer
  num_token_embeddings: -1
  num_pos_embeddings: 512
  num_type_embeddings: 2
  num_turn_embeddings: 16
  num_act: 20
  num_heads: 12
  num_layers: 12
  hidden_dim: 768
  padding_idx: 0
  dropout: 0.1
  embed_dropout: 0.0
  attn_dropout: 0.1
  ff_dropout: 0.1
  use_discriminator: false
  dis_ratio: 1.0
  bce_ratio: 1.0
  pos_trainable: true
  with_joint_act: false
  with_rdrop_act: false
  initializer_range: 0.02
  lr: 0.0001
  weight_decay: 0.0
  gradient_accumulation_steps: 1
  warmup_steps: -1
  max_grad_norm: 5.0

Generator:
  generator: BeamSearch
  min_gen_len: 1
  max_gen_len: 30
  use_true_prev_bspn: false
  use_true_prev_aspn: false
  use_true_db_pointer: false
  use_true_prev_resp: false
  use_true_curr_bspn: false
  use_true_curr_aspn: false
  use_all_previous_context: true
  use_true_bspn_for_ctr_eval: true
  use_true_domain_for_ctr_eval: true
  beam_size: 1
  length_average: false
  length_penalty: -1.0
  ignore_unk: true