# model config
model:
  model_name: soloist-domain-001
  model_dir: ../../data/multiwoz/model/soloist-domain-001
  max_length: 512
  max_context_length: 460
  max_turn: 15
  recommend_coefficient: !!float 1.0

# tokenizer config
tokenizer:
  special_tokens: data/multiwoz/soloist_tokenizer/special_tokens.txt
  eos_token: <|endoftext|>

# inference config
inference:
  num_sample: 5
  temperature: !!float 1.0
  repetition_penalty: !!float 1.0
  top-k: 0
  top-p: !!float 0.5